directories:
  output: dist
  buildResources: build
appId: net.etalt.m0smarket
publish:
  - provider: github
    owner: Nepherian
    repo: m0s-update
extraResources:
  - from: cee/
    to: cee
    filter:
      - '**/*'
win:
  target:
    - nsis
  artifactName: ${name}-${version}-win.${ext}
nsis:
  oneClick: true
mac:
  target:
    - dmg
linux:
  target:
    - AppImage
files: []
electronVersion: 37.7.0
